const express = require("express")
const { cretIncident, getIncident, getMyIncident, getIncidentId, UpdateIncident, assignMem, getIncidentActive, getIncidentStats, getIncidentSLA, getSeverityAnalytics, getResolutionAnalytics, getEngineerWorkload, getSlaAnalytics, getIncidentsPerDay, uploadAttachment, getAttachment, downloadAttachment, deleteAttachment} = require("../controller/incidentController")
const { protect } = require("../middleware/authMiddleware")
const { authorizedSeg } = require("../middleware/roleMiddleware")
const upload = require("../middleware/UploadMiddleware")

const router = express.Router()
router.post("/", protect, authorizedSeg("admin", "engineer"), cretIncident)
router.get("/", protect, getIncident)
router.get("/my-incident", protect, authorizedSeg("admin", "engineer"), getMyIncident)
router.get("/stats", protect, getIncidentStats)
router.get("/analytics/severity", protect, getSeverityAnalytics)
router.get("/analytics/resoln-time", protect, getResolutionAnalytics)
router.get("/analytics/engineer-workload", protect, getEngineerWorkload)
router.get("/analytics/sla", protect, getSlaAnalytics)
router.get("/analytics/incident-per-day", protect, getIncidentsPerDay)
router.get("/attachment/:attachmentId/download", protect, downloadAttachment)
router.delete("/attachment/:attachmentId", protect, authorizedSeg("admin", "engineer"), deleteAttachment)
router.post("/:id/attachment", protect, authorizedSeg("admin", "engineer"), upload.single("file"), uploadAttachment)
router.get("/:id", protect, getIncidentId)
router.get("/:id/activite", protect, getIncidentActive)
router.get("/:id/sla", protect, getIncidentSLA)
router.get("/:id/attachment", protect, getAttachment)
router.put("/:id", protect, authorizedSeg("admin", "engineer"), UpdateIncident)
router.put("/:id/assign", protect, authorizedSeg("admin", "engineer"), assignMem)

module.exports = router